CREATE DATABASE gcb;
use gcb;
CREATE TABLE admins (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(16));
CREATE TABLE safelist (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(16));
